apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: hello-app
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: hello-app
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: hello-app
spec:
  selector:
    matchLabels:
      app: hello-app
      tier: frontend
  replicas: 4
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-app
        tier: frontend
    spec:
      containers:
      - name: hello-app
        image: adrianbranescu93/hello-app:1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      - name: hello-nginx
        image: adrianbranescu93/hello-nginx:2.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
