apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: hello-app
    tier: frontend
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 80
  selector:
    app: hello-app
    tier: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-pvc
  labels:
    app: hello-app
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: hello-app
spec:
  selector:
    matchLabels:
      app: hello-app
      tier: frontend
  replicas: 4
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-app
        tier: frontend
    spec:
      containers:
      - name: hello-app
        image: adrianbranescu93/hello-app:1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      - name: hello-nginx
        image: adrianbranescu93/hello-nginx:2.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hello-pv
          mountPath: /data
      volumes:
      - name: hello-pv
        persistentVolumeClaim:
          claimName: hello-pvc
